### ISSUE TITLE
Error generating a formula for FoBiS.py

### ISSUE THREAD

**Issue by zbeekman** [tdsmith/homebrew-pypi-poet#14]
Hi,
I’m trying to generate a formula for FoBiS.py and am encountering the following error:

```bash
$ poet -f FoBiS.py
Traceback (most recent call last):
  File "/usr/local/bin/poet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/poet/poet.py", line 184, in main
    print(formula_for(args.formula))
  File "/usr/local/lib/python2.7/site-packages/poet/poet.py", line 141, in formula_for
    root = nodes[package]
KeyError: ‘FoBiS.py’
```

Do you know if there is a work around for this? I think it may be a bug.

**Comment by tdsmith** [comment]
Thanks for reporting! This should be fixed in v0.5.1.
