### ISSUE TITLE
Fails for entrypoints

### ISSUE THREAD

**Issue by cglong** [tdsmith/homebrew-pypi-poet#54]
I'm trying to generate `resource` blocks for `jupyter`, but receiving a failure for the `entrypoints` dependency. Note that I receive a similar message for `poet -s entrypoints`:
```
(tmp-bdd0011f9f08ece1) bash-3.2$ poet jupyter
/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py:97: PackageVersionNotFoundWarning: Could not find an exact version match for entrypoints version 0.2.2; using newest instead
  format(name, version), PackageVersionNotFoundWarning)
Traceback (most recent call last):
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/bin/poet", line 11, in <module>
    sys.exit(main())
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py", line 250, in main
    print(resources_for([package] + args.also))
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py", line 175, in resources_for
    nodes = merge_graphs(make_graph(p) for p in packages)
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py", line 182, in merge_graphs
    for g in graphs:
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py", line 175, in <genexpr>
    nodes = merge_graphs(make_graph(p) for p in packages)
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py", line 142, in make_graph
    package_data = research_package(package, dependencies[package]['version'])
  File "/Users/chrislong/.virtualenvs/tmp-bdd0011f9f08ece1/lib/python2.7/site-packages/poet/poet.py", line 105, in research_package
    d['url'] = artefact['url']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by cglong** [comment]
Never mind, I see this is a known issue per #29; hopefully such an important package as `jupyter` will bump priority on that issue 😄

**Comment by tdsmith** [comment]
Please ask them to publish an sdist.
